version: 2
jobs:
  build:
#    environment:
#      - GOPATH: /go
#      - PATH: $GOPATH/bin:/usr/local/go/bin:$PATH
    docker:
      - image: circleci/golang:1.12

    working_directory: /src
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./src/...